name = "VertexEliminationOrder"
uuid = "4f11687a-4218-443e-a9dd-29b5bb0373a4"
authors = ["Valentin Trophime <theval358@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
